### ISSUE TITLE
[Bug] Image version 0.116.0 is not available

### ISSUE THREAD

**Issue by beiertu-mms** [jbangdev/jbang-action#35]
[The build](https://github.com/jbangdev/jbang-action/actions/runs/8505461801/job/23293979418) for the version `0.116.0` has failed and therefore, the image hasn't been pushed.
But some metadata has already been released and so they are picked up by dependabot.
And it creates pull request, which will lead to error.

**Comment by jtama** [comment]
The same is tru with mend

**Comment by jtama** [comment]
Actually the 0.116.0 image is still unavailable

**Comment by beiertu-mms** [comment]
> Actually the 0.116.0 image is still unavailable

I made a mistake with the first fix, so there's currently a second attempt with #37
