### ISSUE TITLE
Make ghcr.io/jbangdev/jbang-action:0.116.0 available

### ISSUE THREAD

**Issue by koppor** [jbangdev/jbang-action#38]
At https://github.com/jbangdev/jbang-action/releases/tag/v0.116.0, there is a tag. This causes dependabot filing a pull request. Example: https://github.com/gi-ev/LNI/pull/167

I get following output

```
  /usr/bin/docker pull ghcr.io/jbangdev/jbang-action:0.116.0
  Error response from daemon: manifest unknown
```

I checked https://github.com/jbangdev/jbang-action/releases, but there is no 0.116.0 release. 

At https://github.com/orgs/jbangdev/packages/container/package/jbang-action, there is no package for 0.116.0.

Would it be possible to publish the release 0.116.0 also as package?

**Comment by jtama** [comment]
Due to https://github.com/jbangdev/jbang-action/actions/runs/8505461801

**Comment by koppor** [comment]
Yeah, if there is no trust, there should be no release 🤣

```
=== RUN: Command Test: Does trust work
--- FAIL
```

---

    Error: Expected string 'Adding .https://github.com/jruby. to /jbang/.jbang/trusted-sources.json' not found in error '[jbang] Trusting permanently: [https://github.com/jruby]

**Comment by koppor** [comment]
@jtama The linked build output is not available any more. Maybe, you could create it? (Maybe, you could also check https://github.com/jbangdev/jbang-action/pull/39 ^^)

**Comment by jtama** [comment]
Sorry i can't do anything on this repository/

@maxandersen  Could you please re-launch the release process.

**Comment by maxandersen** [comment]
i missed this - releasing 0.117 - should let us see where in the release chain things goes wrong (if still issue)

**Comment by koppor** [comment]
Worked fine with 0.177.1 - https://github.com/koppor/github-contributors-list/pull/21

Thus closing this as obsolete.
