### ISSUE TITLE
Mention "Warning: EACCES: permission denied, lstat '/root/.jbang'"

### ISSUE THREAD

**Issue by koppor** [jbangdev/jbang-action#40]
When running the action, I get

```
Post job cleanup.
Warning: EACCES: permission denied, lstat '/root/.jbang'
```

![grafik](https://github.com/user-attachments/assets/9734e7ee-6e1e-4e97-a098-59257d636d47)

I think, there should be no Warning.

Proposal: Mention it in `README.md` or try to remove the warning :).

**Comment by maxandersen** [comment]
Where/how to reproduce this ?

**Comment by koppor** [comment]
Checked latest run: https://github.com/JabRef/jabref/actions/runs/10797089627/job/29947559133

Did not happen, thus closing. I will reopen if it occurs again.
